server:
  port: 8080
  servlet:
    context-path: /spring-security-boot

spring:
  application:
    name: spring-security-boot

  thymeleaf:
    prefix: classpath:/view/
    suffix: .html
    check-template-location: true
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/spring-security-learn?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver