server:
  port: 8080
  servlet:
    context-path: /spring-security-boot

spring:
  application:
    name: spring-security-boot

  thymeleaf:
    prefix: classpath:/view/
    suffix: .html
    check-template-location: true
    cache: false